### ISSUE TITLE
I cannot get search by tags to work

### ISSUE THREAD

**Issue by tuxtlequino** [chrillek/DT-Search-JS#1]
Nothing in the debug window to help point. But this is the query
{"items":[{"query":"tags: tax "}]}

And I can try to go around to do the same by first listing all the tags in a database, then searching that database by the selected tag. The JSON request is the same in the debug window, and still no results.
{"items":[{"query":"tags: tax "}]}

Hope this helps

**Comment by chrillek** [comment]
How exactly are you searching for tags. Here
- DTT with tag works
- DTS with query 'tags:<tag>' (without the pointy brackets, of course) works
- DTD, listing all tags of database and then select one tag works
Which version of the workflow do you use?

**Comment by tuxtlequino** [comment]
None of the ways to search for tags included above were working. I was recording a video to show you why, but trying to conceal some private information, I think I figure it out. I added a tag, and then it appeared. It seems as if most of my tags didn't have any files tagged. No clue how did that happened. After cleaning my databases, everything works. Thank you!
