### ISSUE TITLE
DT-Search-JS reverts to a default web search when most commands are entered

### ISSUE THREAD

**Issue by philp2** [chrillek/DT-Search-JS#2]
1. I'm using a Macbook Pro with M1 chip running Ventura, latest versions of Alfred 5 and DT-Search-JS extension for Alfred, and latest version of Devonthink 3.
2. I open the Alfred window and start to type a command but in most all cases once I select a second or third letter, like n or t in "dnt", it goes to a default web search via google, etc.  "dtts" does open a query correctly in DT and is the only command that works that I've found.  For another example of a failure, when entering the dt portion of "dtd", a list of commands from the extension appears but selecting the "show all databases" entry OR typing the final d causes it to go to a web search again in either case.

**Comment by chrillek** [comment]
There is no keyboard shortcut "dnt". Where did you take that from? 
"dtd" shows all databases here, select one by pressing Cmd+1, Cmd+2 etc or return for the first one.
_How_ do you select "get all databases" (there'e no "show all databases" in this context).

**Comment by philp2** [comment]
Sorry, my mistake on dnt.  Entering dtd just goes to the default search whether I select it from the list of commands after typing just dt or enter all three letters.  I'm unsure what you are recommending.

**Comment by chrillek** [comment]
Do you use the workflow from github or did you download it from somewhere else?

**Comment by philp2** [comment]
From GitHub. On Feb 1, 2023, at 2:23 AM, chrillek ***@***.***> wrote:﻿
Do you use the workflow from github or did you download it from somewhere else?

**Comment by philp2** [comment]
chrillek - I found the problem after trying a number of different things.  In Mac Preferences/Privacy & Security/Automation I had to add the Devonthink 3 app under Alfred 5 so that it could control DT.  Once I did that, it worked as expected.  Thanks for a great workflow and for your assistance.

**Comment by chrillek** [comment]
Thanks for finding the cause of that. I'll update the README accordingly.
